cursor #dae4ec
cursor_text_color #bec8d0

foreground            #dae4ec
background            #0b141a
selection_foreground  #1b324b
selection_background  #b2c8e8
url_color             #82cfff
color0   #0b141a
color1   #e64c4a
color2   #73d66e
color3   #dbcf7b
color4   #3589be
color5   #74a2bf
color6   #82cfff
color7   #abb2bf
color8   #5c6370
color9   #e05f62
color10   #8ae086
color11   #e8dd97
color12   #8adeff
color13   #388599
color14   #587ca5
color15   #ffffff
