[org/gnome/desktop/wm/keybindings]
close=['<Super>q']
switch-input-source=['XF86Keyboard']
switch-input-source-backward=['<Shift>XF86Keyboard']

[org/freedesktop/ibus/general/hotkey]
triggers=@as []

[org/gnome/desktop/default-applications/terminal]
exec='kitty'
exec-arg='--'

[com/github/stunkymonkey/nautilus-open-any-terminal]
terminal='kitty'
new-tab=false

[org/gnome/settings-daemon/plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/ulauncher/']

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/ulauncher]
binding='<Super>space'
command='ulauncher-toggle'
name='Ulauncher'
