exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = bash -c "wl-paste --watch cliphist store &"
exec-once = dms run
exec-once = hyprctl setcursor phinger-cursors-dark 24
exec-once = hyprpm reload -n
exec-once = 1password --silent
exec-once = ~/dotfiles/arch/scripts/restart_bluetooth
exec-once = protonmail-bridge --no-window
exec-once = protonvpn-app --start-minimized
