windowrule = rounding 12 match:class ^(org\.gnome\.)
windowrule = border_size 0 match:class ^(org\.gnome\.)

windowrule = tile match:class ^(gnome-control-center)$
windowrule = tile match:class ^(pavucontrol)$
windowrule = tile match:class ^(nm-connection-editor)$
windowrule = tile match:class ^(org.pulseaudio.pavucontrol)$

windowrule = float match:class ^(blueman-manager)$
windowrule = float match:class ^(system-config-printer)$
windowrule = float match:class ^(xsensors)$
windowrule = float match:title ^(Calculator)$
windowrule = float center match:class ^(org.raspberrypi.rpi-imager)$
windowrule = float match:class ^(xdg-desktop-portal)$

windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = size (monitor_w*0.25) (monitor_w*0.25*9/16), match:title ^(Picture-in-Picture)$
windowrule = keep_aspect_ratio on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = opaque on, match:title ^(Picture-in-Picture)$
windowrule = move (monitor_w-window_w-5) (monitor_h-window_h-5), match:title ^(Picture-in-Picture)$
windowrule = fullscreen match:title ^(Counter-Strike 2)(.*)$

windowrule = opacity 0.9 0.9 match:float 0 match:focus 0

layerrule = no_anim match:namespace ^(quickshell)$
