-- Hyprland config (lua) - migrated from hyprlang on 2026-05-11.
-- Hyprland >= 0.55 prefers ~/.config/hypr/hyprland.lua over hyprland.conf.
-- Reference: https://wiki.hypr.land/Configuring/Start/

----------------------------------------------------------------------
-- MONITORS
----------------------------------------------------------------------
-- Generated by nwg-displays on 2025-12-22; mirror that layout here.
hl.monitor({
    output   = "DP-1",
    mode     = "2560x1440@180.0",
    position = "0x1440",
    scale    = 1.0,
})
hl.monitor({
    output    = "HDMI-A-1",
    mode      = "1920x1080@74.97",
    position  = "2560x1160",
    scale     = 1.0,
    transform = 3,
})

----------------------------------------------------------------------
-- ENVIRONMENT
----------------------------------------------------------------------
hl.env("WLR_NO_HARDWARE_CURSORS",       "1")
hl.env("WLR_RENDERER_ALLOW_SOFTWARE",   "1")
hl.env("XCURSOR_SIZE",                  "24")
hl.env("WLR_DRM_NO_ATOMIC",             "1")
hl.env("QT_QPA_PLATFORM",               "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT",  "auto")
hl.env("QT_QPA_PLATFORMTHEME",          "gtk3")
hl.env("QT_QPA_PLATFORMTHEME_QT6",      "gtk3")
hl.env("TERMINAL",                      "kitty")

-- Cursor (was dms/cursor.conf, auto-generated by DMS in hyprlang format).
-- Inlined here because lua configs do not source .conf files.
hl.env("HYPRCURSOR_THEME", "phinger-cursors-dark")
hl.env("XCURSOR_THEME",    "phinger-cursors-dark")
hl.env("HYPRCURSOR_SIZE",  "24")
hl.env("XCURSOR_SIZE",     "24")

----------------------------------------------------------------------
-- AUTOSTART
----------------------------------------------------------------------
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("dms run")
    hl.exec_cmd("hyprctl setcursor phinger-cursors-dark 24")
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("1password --silent")
    hl.exec_cmd(os.getenv("HOME") .. "/dotfiles/arch/scripts/restart_bluetooth")
    hl.exec_cmd("protonmail-bridge --no-window")
    hl.exec_cmd("protonvpn-app --start-minimized")
    -- Watch DMS-generated dms/*.conf and re-apply via lua at runtime.
    hl.exec_cmd(os.getenv("HOME") .. "/dotfiles/arch/scripts/dms-hypr-watcher.sh")
end)

----------------------------------------------------------------------
-- LOOK AND FEEL
----------------------------------------------------------------------
hl.config({
    general = {
        gaps_in     = 5,
        gaps_out    = 5,
        border_size = 2,
        col = {
            active_border   = "0xffcba6f7",
            inactive_border = "rgba(ffffffff)",
        },
        layout        = "dwindle",
        allow_tearing = false,
    },

    decoration = {
        rounding           = 8,
        active_opacity     = 1.0,
        inactive_opacity   = 0.8,
        fullscreen_opacity = 1.0,

        blur = {
            enabled           = true,
            size              = 12,
            passes            = 4,
            new_optimizations = true,
            ignore_opacity    = true,
            xray              = true,
        },

        shadow = {
            enabled      = true,
            range        = 30,
            render_power = 5,
            offset       = { 0, 5 },
            color        = "rgba(00000070)",
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
        -- pseudotile is no longer a config option; use hl.dsp.window.pseudo() bind.
    },

    master = {
        mfact = 0.5,
    },

    misc = {
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
        vrr                      = 1,
    },

    xwayland = {
        force_zero_scaling = true,
    },

    ecosystem = {
        no_update_news = true,
    },

    debug = {
        full_cm_proto = true,
        disable_logs  = false,
    },
})

----------------------------------------------------------------------
-- ANIMATIONS
----------------------------------------------------------------------
-- Keep simple: speeds + default bezier, matching the previous hyprlang config.
hl.animation({ leaf = "windowsIn",   enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "fade",        enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border",      enabled = true, speed = 3, bezier = "default" })

----------------------------------------------------------------------
-- INPUT
----------------------------------------------------------------------
hl.config({
    input = {
        kb_layout          = "us",
        kb_variant         = "intl",
        kb_model           = "",
        kb_options         = "caps:escape_shifted_capslock",
        kb_rules           = "",
        numlock_by_default = true,
        follow_mouse       = 1,
        sensitivity        = -1,
        scroll_factor      = 0.8,
        accel_profile      = "adaptive",
        natural_scroll     = false,
    },
    cursor = {
        no_hardware_cursors = false,
    },
})

hl.device({
    name        = "logitech-g903-ls-1",
    sensitivity = -0.85,
})

----------------------------------------------------------------------
-- WORKSPACES
----------------------------------------------------------------------
hl.workspace_rule({ workspace = "1",  monitor = "DP-1", default = true })
hl.workspace_rule({ workspace = "2",  monitor = "DP-1" })
hl.workspace_rule({ workspace = "3",  monitor = "DP-1" })
hl.workspace_rule({ workspace = "4",  monitor = "DP-1" })
hl.workspace_rule({ workspace = "5",  monitor = "DP-1" })
hl.workspace_rule({ workspace = "6",  monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "7",  monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "8",  monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "9",  monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "10", monitor = "HDMI-A-1" })

----------------------------------------------------------------------
-- WINDOW RULES
----------------------------------------------------------------------
-- Gnome apps: extra rounding, no border.
hl.window_rule({
    name  = "gnome-rounding",
    match = { class = "^(org\\.gnome\\.)" },
    rounding    = 12,
    border_size = 0,
})

-- Tile certain config-style apps.
hl.window_rule({ match = { class = "^(gnome-control-center)$" },        tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" },                 tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" },        tile = true })
hl.window_rule({ match = { class = "^(org.pulseaudio.pavucontrol)$" },  tile = true })

-- Float specific apps/dialogs.
hl.window_rule({ match = { class = "^(blueman-manager)$" },         float = true })
hl.window_rule({ match = { class = "^(system-config-printer)$" },   float = true })
hl.window_rule({ match = { class = "^(xsensors)$" },                float = true })
hl.window_rule({ match = { title = "^(Calculator)$" },              float = true })
hl.window_rule({
    match  = { class = "^(org.raspberrypi.rpi-imager)$" },
    float  = true,
    center = true,
})
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" },      float = true })

-- Picture-in-Picture: float, sized, pinned, opaque, snapped to bottom-right.
hl.window_rule({
    name  = "pip",
    match = { title = "^(Picture-in-Picture)$" },
    float             = true,
    size              = { "monitor_w*0.25", "monitor_w*0.25*9/16" },
    keep_aspect_ratio = true,
    pin               = true,
    opaque            = true,
    move              = { "monitor_w-window_w-5", "monitor_h-window_h-5" },
})

-- CS2 fullscreen.
hl.window_rule({
    match      = { title = "^(Counter-Strike 2)(.*)$" },
    fullscreen = true,
})

-- Dim unfocused floating windows.
hl.window_rule({
    name    = "dim-unfocused-floats",
    match   = { float = true, focus = false },
    opacity = "0.9 0.9",
})

----------------------------------------------------------------------
-- LAYER RULES
----------------------------------------------------------------------
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })

----------------------------------------------------------------------
-- KEYBINDINGS
----------------------------------------------------------------------
local mod = "SUPER"

-- Application launchers
hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd("kitty"))
hl.bind(mod .. " + E",      hl.dsp.exec_cmd("nautilus"))
hl.bind(mod .. " + B",      hl.dsp.exec_cmd("zen-browser"))
hl.bind(mod .. " + space",  hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
hl.bind(mod .. " + V",      hl.dsp.exec_cmd("dms ipc call clipboard toggle"))
hl.bind(mod .. " + M",      hl.dsp.exec_cmd("dms ipc call processlist toggle"))
hl.bind(mod .. " + comma",  hl.dsp.exec_cmd("dms ipc call settings toggle"))
hl.bind(mod .. " + N",      hl.dsp.exec_cmd("dms ipc call notifications toggle"))
hl.bind(mod .. " + SHIFT + N", hl.dsp.exec_cmd("dms ipc call notepad toggle"))
hl.bind(mod .. " + Y",      hl.dsp.exec_cmd("dms ipc call dankdash wallpaper"))
hl.bind(mod .. " + TAB",    hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))

-- Security
hl.bind(mod .. " + CTRL + Q",  hl.dsp.exec_cmd("dms ipc call powermenu toggle"))
hl.bind(mod .. " + CTRL + L",  hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("dms ipc call processlist toggle"))

-- Audio
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 3"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 3"), { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("dms ipc call audio mute"),        { locked = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("dms ipc call audio micmute"),     { locked = true })

-- Brightness
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd('dms ipc call brightness increment 5 ""'), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd('dms ipc call brightness decrement 5 ""'), { locked = true, repeating = true })

-- Window management
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
hl.bind(mod .. " + T", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + W", hl.dsp.group.toggle())
-- Note: `mod + P` was bound twice in old config (pin + submap); submap wins below.

-- Focus navigation
hl.bind(mod .. " + left",  hl.dsp.focus({ direction = "l" }))
hl.bind(mod .. " + down",  hl.dsp.focus({ direction = "d" }))
hl.bind(mod .. " + up",    hl.dsp.focus({ direction = "u" }))
hl.bind(mod .. " + right", hl.dsp.focus({ direction = "r" }))
hl.bind(mod .. " + H",     hl.dsp.focus({ direction = "l" }))
hl.bind(mod .. " + J",     hl.dsp.focus({ direction = "d" }))
hl.bind(mod .. " + K",     hl.dsp.focus({ direction = "u" }))
hl.bind(mod .. " + L",     hl.dsp.focus({ direction = "r" }))

-- Window movement (note: this collides with monitor focus in old config; window movement wins)
hl.bind(mod .. " + CTRL + left",  hl.dsp.window.move({ direction = "l" }))
hl.bind(mod .. " + CTRL + down",  hl.dsp.window.move({ direction = "d" }))
hl.bind(mod .. " + CTRL + up",    hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + CTRL + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mod .. " + CTRL + H",     hl.dsp.window.move({ direction = "l" }))
hl.bind(mod .. " + CTRL + J",     hl.dsp.window.move({ direction = "d" }))
hl.bind(mod .. " + CTRL + K",     hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + CTRL + L",     hl.dsp.window.move({ direction = "r" }))

-- Move window to monitor (direction)
hl.bind(mod .. " + SHIFT + CTRL + left",  hl.dsp.window.move({ monitor = "l" }))
hl.bind(mod .. " + SHIFT + CTRL + down",  hl.dsp.window.move({ monitor = "d" }))
hl.bind(mod .. " + SHIFT + CTRL + up",    hl.dsp.window.move({ monitor = "u" }))
hl.bind(mod .. " + SHIFT + CTRL + right", hl.dsp.window.move({ monitor = "r" }))
hl.bind(mod .. " + SHIFT + CTRL + H",     hl.dsp.window.move({ monitor = "l" }))
hl.bind(mod .. " + SHIFT + CTRL + J",     hl.dsp.window.move({ monitor = "d" }))
hl.bind(mod .. " + SHIFT + CTRL + K",     hl.dsp.window.move({ monitor = "u" }))
hl.bind(mod .. " + SHIFT + CTRL + L",     hl.dsp.window.move({ monitor = "r" }))

-- Workspace navigation (relative across open workspaces)
hl.bind(mod .. " + Page_Down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + Page_Up",   hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + U",         hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + I",         hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + SHIFT + Page_Down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mod .. " + SHIFT + Page_Up",   hl.dsp.window.move({ workspace = "e-1" }))
hl.bind(mod .. " + SHIFT + U",         hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mod .. " + SHIFT + I",         hl.dsp.window.move({ workspace = "e-1" }))

-- Mouse wheel workspace navigation
hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + CTRL + mouse_down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mod .. " + CTRL + mouse_up",   hl.dsp.window.move({ workspace = "e-1" }))

-- Numbered workspaces
for i = 1, 10 do
    local key = (i == 10) and "0" or tostring(i)
    hl.bind(mod .. " + " .. key,           hl.dsp.focus({ workspace = i }))
    hl.bind(mod .. " + SHIFT + " .. key,   hl.dsp.window.move({ workspace = i }))
end

-- Column / split management (dwindle)
hl.bind(mod .. " + bracketleft",  hl.dsp.layout("preselect l"))
hl.bind(mod .. " + bracketright", hl.dsp.layout("preselect r"))
hl.bind(mod .. " + R",            hl.dsp.layout("togglesplit"))
hl.bind(mod .. " + CTRL + F",     hl.dsp.window.fullscreen({ mode = "maximized" }))

-- Mouse drag/resize
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true, description = "Move window" })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Resize window" })
-- PiP corner snap on drag end (fires on mouse:272 release).
hl.bind(mod .. " + mouse:272",
    hl.dsp.exec_cmd(os.getenv("HOME") .. "/dotfiles/arch/scripts/pip-snap-corner.sh"),
    { mouse = true, release = true, description = "Snap PiP to corner on drag end" })

-- Resize via keyboard (code:20 = -, code:21 = =)
hl.bind(mod .. " + code:20", hl.dsp.window.resize({ x = -100, y =    0, relative = true }), { description = "Expand window left" })
hl.bind(mod .. " + code:21", hl.dsp.window.resize({ x =  100, y =    0, relative = true }), { description = "Shrink window left" })
hl.bind(mod .. " + SHIFT + right", hl.dsp.window.resize({ x =  100, y =    0, relative = true }))
hl.bind(mod .. " + SHIFT + left",  hl.dsp.window.resize({ x = -100, y =    0, relative = true }))
hl.bind(mod .. " + SHIFT + up",    hl.dsp.window.resize({ x =    0, y = -100, relative = true }))
hl.bind(mod .. " + SHIFT + down",  hl.dsp.window.resize({ x =    0, y =  100, relative = true }))

-- Screenshots
local screenshot = os.getenv("HOME") .. "/.local/bin/screenshot"
hl.bind("XF86Launch1",                 hl.dsp.exec_cmd(screenshot .. " area"))
hl.bind("CTRL + XF86Launch1",          hl.dsp.exec_cmd(screenshot .. " screen"))
hl.bind("ALT + XF86Launch1",           hl.dsp.exec_cmd(screenshot .. " active"))
hl.bind("SHIFT + XF86Launch1",         hl.dsp.exec_cmd(screenshot .. " area-annotate"))
hl.bind("Print",                       hl.dsp.exec_cmd(screenshot .. " area"))
hl.bind("CTRL + Print",                hl.dsp.exec_cmd(screenshot .. " screen"))
hl.bind("ALT + Print",                 hl.dsp.exec_cmd(screenshot .. " active"))
hl.bind("SHIFT + Print",               hl.dsp.exec_cmd(screenshot .. " area-annotate"))
hl.bind("CTRL + SHIFT + Print",        hl.dsp.exec_cmd(screenshot .. " screen-annotate"))
hl.bind("ALT + SHIFT + Print",         hl.dsp.exec_cmd(screenshot .. " active-annotate"))

-- DPMS off
hl.bind(mod .. " + SHIFT + P", hl.dsp.dpms({ action = "disable" }))

-- Passthru submap (mod+P enters it; mod+Escape exits)
hl.bind(mod .. " + P", hl.dsp.submap("passthru"))
hl.define_submap("passthru", function()
    hl.bind(mod .. " + Escape", hl.dsp.submap("reset"))
end)
