local cfg = os.getenv("HOME") .. "/dotfiles/arch/hypr/lua/"

dofile(cfg .. "monitors.lua")
dofile(cfg .. "env.lua")
dofile(cfg .. "autostart.lua")
dofile(cfg .. "appearance.lua")
dofile(cfg .. "input.lua")
dofile(cfg .. "workspaces.lua")
dofile(cfg .. "windowrules.lua")
dofile(cfg .. "keybindings.lua")
dofile(cfg .. "cursor.lua")
dofile(cfg .. "noctalia-layout.lua")
dofile(cfg .. "noctalia-windowrules.lua")

-- Noctalia-generated theme colors (regenerated by Noctalia's Hyprland template)
require("noctalia").apply_theme()
