$file_manager=nautilus

source = ~/dotfiles/arch/hypr/monitors.conf
source = ~/dotfiles/arch/hypr/conf/1-env.conf
source = ~/dotfiles/arch/hypr/conf/2-startup.conf
source = ~/dotfiles/arch/hypr/conf/3-input.conf
source = ~/dotfiles/arch/hypr/conf/4-decoration.conf
source = ~/dotfiles/arch/hypr/conf/5-animations.conf
source = ~/dotfiles/arch/hypr/conf/6-layouts.conf
source = ~/dotfiles/arch/hypr/conf/7-misc.conf
source = ~/dotfiles/arch/hypr/conf/8-windowrules.conf
source = ~/dotfiles/arch/hypr/conf/9-workspaces.conf
source = ~/dotfiles/arch/hypr/conf/10-keybindings.conf
source = ~/dotfiles/arch/hypr/conf/11-debug.conf
# source = ~/dotfiles/arch/hypr/conf/12-plugins.conf

# DMS-related shenanigans
source = ./dms/cursor.conf
# source = ./dms/colors.conf
# source = ./dms/layout.conf
# source = ./dms/outputs.conf
# source = ./dms/windowrules.conf
