-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "phinger-cursors-dark")
hl.env("XCURSOR_THEME", "phinger-cursors-dark")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_SIZE", "24")
